#undef reach_main_window_setup_spinbox
#undef reach_main_window_setup_flag_checkbox
#undef reach_main_window_setup_bool_checkbox
#undef reach_main_window_setup_spinbox
#undef reach_main_window_setup_spinbox_dbl

#undef reach_traits_pane_setup_combobox
#undef reach_traits_pane_setup_spinbox

#undef reach_team_pane_setup_flag_checkbox
#undef reach_team_pane_setup_combobox
#undef reach_team_pane_setup_spinbox