#define WIDGET_NAME RVTArmorAbilityPicker
#include "./_interface_boilerplate.inl"
#include INTERFACE_FILE
#include WIDGET_FILE

DEFINE_DEFAULT_CONSTRUCTION;
DEFINE_DEFAULT_INITIALIZATION;
DEFINE_BOILERPLATE_GETTERS(armorAbility);

DEFINE_DEFAULT_WIDGET_CONSTRUCTOR;
DEFINE_DEFAULT_NAME_GETTER;
DEFINE_DEFAULT_GROUP_GETTER;
DEFINE_DEFAULT_ICON_GETTER;
DEFINE_TOOLTIP_TEXT_GETTER("A widget that can be used to select an Armor Ability, within player traits and loadouts.");
DEFINE_WHATS_THIS_TEXT_GETTER("");