name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      # Installs the Qt SDK
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        dir: ${{ runner.temp }}
        arch: 'win64_msvc2019_64'
        setup-python: true
      
    - name: Download JOM
      uses: suisei-cn/actions-download-file@v1
      with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\

    - name: Unzip JOM
      working-directory: ${{ runner.temp }}
      run:  |
            7z x jom.zip -ojom

    - name: Create build directory
      run:  mkdir ${{ runner.temp }}\build

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Build
      working-directory: ${{ runner.temp }}\build
      run:  |
            cd native/src/ReachVariantTool
            qmake
            nmake
  
    - name: Zip build
      working-directory: ${{ runner.temp }}
      run:  |
            7z a ReachVariantTool.zip ${{ runner.temp }}\build\* -r
  
    - name: Save build artifact
      uses: actions/upload-artifact@master
      with:
        name: ReachVariantTool.zip
        path: ${{ runner.temp }}\ReachVariantTool.zip
